<a href="https://colab.research.google.com/github/limav176/com550/blob/main/Videoaula_6_Pra%CC%81tica_Corpus_e_Similaridade_Textual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# COM550 - Processamento de Linguagem Natural

## Semana 2 - Introdução ao Processamento de Linguagem Natural
## Videoaula 6 - *Corpus* e Similaridade Textual


# Revisão sobre *Corpus*

In [ ]:
poema = """E agora, José?
A festa acabou,
a luz apagou,
o povo sumiu,
a noite esfriou,
e agora, José?
e agora, você?
você que é sem nome,
que zomba dos outros,
você que faz versos,
que ama, protesta?
e agora, José?

Está sem mulher,
está sem discurso,
está sem carinho,
já não pode beber,
já não pode fumar,
cuspir já não pode,
a noite esfriou,
o dia não veio,
o bonde não veio,
o riso não veio,
não veio a utopia
e tudo acabou
e tudo fugiu
e tudo mofou,
e agora, José?

E agora, José?
Sua doce palavra,
seu instante de febre,
sua gula e jejum,
sua biblioteca,
sua lavra de ouro,
seu terno de vidro,
sua incoerência,
seu ódio - e agora?

Com a chave na mão
quer abrir a porta,
não existe porta;
quer morrer no mar,
mas o mar secou;
quer ir para Minas,
Minas não há mais.
José, e agora?

Se você gritasse,
se você gemesse,
se você tocasse
a valsa vienense,
se você dormisse,
se você cansasse,
se você morresse...
Mas você não morre,
você é duro, José!

Sozinho no escuro
qual bicho-do-mato,
sem teogonia,
sem parede nua
para se encostar,
sem cavalo preto
que fuja a galope,
você marcha, José!
José, para onde?"""


In [ ]:
import nltk
from nltk import tokenize
nltk.download('punkt') # necessário para baixar o tokenizador

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

## Contagem de *tokens* e *types*

In [ ]:
tokens = tokenize.word_tokenize(poema, language="portuguese")
minusculas = tokenize.word_tokenize(poema.lower(), language="portuguese")

vocabulario = set(minusculas)

print("Quantidade de tokens: ",len(tokens))
print("Quantidade de types: ",len(vocabulario))

Quantidade de tokens:  274
Quantidade de types:  109


In [ ]:
print(tokens)
print(len(tokens))

['E', 'agora', ',', 'José', '?', 'A', 'festa', 'acabou', ',', 'a', 'luz', 'apagou', ',', 'o', 'povo', 'sumiu', ',', 'a', 'noite', 'esfriou', ',', 'e', 'agora', ',', 'José', '?', 'e', 'agora', ',', 'você', '?', 'você', 'que', 'é', 'sem', 'nome', ',', 'que', 'zomba', 'dos', 'outros', ',', 'você', 'que', 'faz', 'versos', ',', 'que', 'ama', ',', 'protesta', '?', 'e', 'agora', ',', 'José', '?', 'Está', 'sem', 'mulher', ',', 'está', 'sem', 'discurso', ',', 'está', 'sem', 'carinho', ',', 'já', 'não', 'pode', 'beber', ',', 'já', 'não', 'pode', 'fumar', ',', 'cuspir', 'já', 'não', 'pode', ',', 'a', 'noite', 'esfriou', ',', 'o', 'dia', 'não', 'veio', ',', 'o', 'bonde', 'não', 'veio', ',', 'o', 'riso', 'não', 'veio', ',', 'não', 'veio', 'a', 'utopia', 'e', 'tudo', 'acabou', 'e', 'tudo', 'fugiu', 'e', 'tudo', 'mofou', ',', 'e', 'agora', ',', 'José', '?', 'E', 'agora', ',', 'José', '?', 'Sua', 'doce', 'palavra', ',', 'seu', 'instante', 'de', 'febre', ',', 'sua', 'gula', 'e', 'jejum', ',', 'sua', 'b

In [ ]:
print(vocabulario)
print(len(vocabulario))

{'luz', 'noite', 'bonde', 'gula', 'vidro', 'febre', 'utopia', 'gemesse', '...', 'com', 'mar', 'tocasse', '.', 'escuro', 'dormisse', 'bicho-do-mato', 'onde', 'incoerência', 'faz', 'sem', 'abrir', 'mais', 'fuja', 'lavra', 'beber', 'cavalo', ',', 'há', 'na', 'esfriou', 'porta', 'terno', 'carinho', 'instante', 'que', 'morrer', 'qual', 'se', 'cuspir', 'ouro', 'pode', 'preto', 'no', 'está', 'seu', 'veio', 'nome', 'e', 'galope', 'gritasse', 'agora', 'é', 'dia', 'quer', 'parede', 'dos', 'apagou', 'doce', 'outros', 'acabou', 'duro', 'protesta', 'já', 'mão', 'para', 'marcha', 'você', 'minas', 'teogonia', 'tudo', 'de', 'sumiu', 'mofou', 'mas', 'existe', 'o', 'não', 'valsa', ';', '!', 'sua', 'discurso', 'morresse', 'fugiu', 'sozinho', '-', '?', 'palavra', 'biblioteca', 'vienense', 'mulher', 'a', 'riso', 'versos', 'josé', 'povo', 'ama', 'festa', 'ir', 'nua', 'fumar', 'jejum', 'cansasse', 'encostar', 'chave', 'morre', 'zomba', 'ódio', 'secou'}
109


## Segmentação de sentenças

In [ ]:
sentencas = nltk.sent_tokenize(poema, language="portuguese")
print(sentencas)
print(len(sentencas))

['E agora, José?', 'A festa acabou,\na luz apagou,\no povo sumiu,\na noite esfriou,\ne agora, José?', 'e agora, você?', 'você que é sem nome,\nque zomba dos outros,\nvocê que faz versos,\nque ama, protesta?', 'e agora, José?', 'Está sem mulher,\nestá sem discurso,\nestá sem carinho,\njá não pode beber,\njá não pode fumar,\ncuspir já não pode,\na noite esfriou,\no dia não veio,\no bonde não veio,\no riso não veio,\nnão veio a utopia\ne tudo acabou\ne tudo fugiu\ne tudo mofou,\ne agora, José?', 'E agora, José?', 'Sua doce palavra,\nseu instante de febre,\nsua gula e jejum,\nsua biblioteca,\nsua lavra de ouro,\nseu terno de vidro,\nsua incoerência,\nseu ódio - e agora?', 'Com a chave na mão\nquer abrir a porta,\nnão existe porta;\nquer morrer no mar,\nmas o mar secou;\nquer ir para Minas,\nMinas não há mais.', 'José, e agora?', 'Se você gritasse,\nse você gemesse,\nse você tocasse\na valsa vienense,\nse você dormisse,\nse você cansasse,\nse você morresse...', 'Mas você não morre,\nvocê é 

# Similaridade textual

In [1]:
import pandas as pd
import numpy as np

In [2]:
texts = ['O Grêmio é tricampeão da Libertadores da América',
         'O Corinthians ganhou a Libertadores uma única vez']
classes = ['Grêmio', 'Corinthians']

df = pd.DataFrame({'texts': texts, 'classes': classes})
print(df)

                                               texts      classes
0   O Grêmio é tricampeão da Libertadores da América       Grêmio
1  O Corinthians ganhou a Libertadores uma única vez  Corinthians


## Similaridade Textual baseada em caracteres

## A distância de Levenshtein

"Este método foi inventado em 1965 pelo matemático russo Vladimir Levenshtein (1935-2017). O valor da distância descreve o número mínimo de remoções, inserções ou substituições necessárias para transformar uma *string* em outra."

FONTE: [Distância de Levenshtein e similaridade de texto em Python](http://stackabuse.com/levenshtein-distance-and-text-similarity-in-python/)

In [3]:
def levenshtein(seq1, seq2):
    # criar uma matriz
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))

    # setar número de colunas (0, n-1)
    for x in range(size_x):
        matrix [x, 0] = x

    # setar número de linhas (0, n-1)
    for y in range(size_y):
        matrix [0, y] = y

    # calcular a distancia
    for x in range(1, size_x):
        for y in range(1, size_y):
            # se os caracteres sao iguais, nao aumenta a distancia
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = matrix[x-1, y-1]
            # se são diferentes, aumenta a distancia em 1
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )

    # imprime a matriz de calculo da distancia
    # list(seq1) converte string em uma lista de caracteres
    print(pd.DataFrame(matrix[1:,1:], index=list(seq1), columns=list(seq2)))

    return (matrix[size_x - 1, size_y - 1])

In [4]:
levenshtein('amor','calor')

     c    a    l    o    r
a  1.0  1.0  2.0  3.0  4.0
m  2.0  2.0  2.0  3.0  4.0
o  3.0  3.0  3.0  2.0  3.0
r  4.0  4.0  4.0  3.0  2.0


2.0

In [5]:
# Utilizando a distância de Levenshtein para comparar textos/sentenças
print(df)
print ("------")
doc_id_a = 0 # id do texto 1
doc_id_b = 1 # id do texto 2
print("texto 1: ",df.loc[doc_id_a]['texts'])
print("texto 2: ",df.loc[doc_id_b]['texts'])
print ("------")

levenshtein(df.loc[doc_id_a]['texts'],df.loc[doc_id_b]['texts'])

                                               texts      classes
0   O Grêmio é tricampeão da Libertadores da América       Grêmio
1  O Corinthians ganhou a Libertadores uma única vez  Corinthians
------
texto 1:  O Grêmio é tricampeão da Libertadores da América
texto 2:  O Corinthians ganhou a Libertadores uma única vez
------
      O           C     o     r     i     n     t     h     i  ...        \
O   0.0   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  ...  39.0   
    1.0   0.0   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0  ...  38.0   
G   2.0   1.0   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0  ...  38.0   
r   3.0   2.0   2.0   2.0   2.0   3.0   4.0   5.0   6.0   7.0  ...  37.0   
ê   4.0   3.0   3.0   3.0   3.0   3.0   4.0   5.0   6.0   7.0  ...  37.0   
m   5.0   4.0   4.0   4.0   4.0   4.0   4.0   5.0   6.0   7.0  ...  36.0   
i   6.0   5.0   5.0   5.0   5.0   4.0   5.0   5.0   6.0   6.0  ...  36.0   
o   7.0   6.0   6.0   5.0   6.0   5.0   5.0   6.0   6.0   7.0

29.0

## Similaridade Textual baseada em Termos

### Vetorizando os documentos de treinamento

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
"""Criando o objeto vetorizador (convertendo para letras minúsculas, removendo as stopwords especificadas em uma lista
   e apenas mantendo os termos que ocorreram em dois ou mais documentos"""
vetorizador = CountVectorizer(lowercase=True,
                              stop_words=['is', 'are', 'a', 'or', 'to', 'in', 'the', 'so', 'since', 'many', 'of'],
                              min_df=2,
                              dtype=np.int16
                              )

In [7]:
# Obtendo o vocabulário
vetorizador.fit(df['texts'])

CountVectorizer(dtype=<class 'numpy.int16'>, min_df=2,
                stop_words=['is', 'are', 'a', 'or', 'to', 'in', 'the', 'so',
                            'since', 'many', 'of'])

In [8]:
# Gerando a representação estruturada a partir do vocabulário ajustado
representacao = vetorizador.transform(df['texts'])
# A representação retornada é uma matriz em um formato esparso  (posso gerar o array usando toArray())
representacao
rep_array = representacao.toarray() # a partir daqui podemos aplicar as funções de similaridade
print(rep_array)

[[1]
 [1]]


### Cosseno

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
matrix_sim = cosine_similarity(rep_array)

In [10]:
matrix_sim

array([[1., 1.],
       [1., 1.]])

In [11]:
def most_similar(id_doc, matrix):
  matrix_sim = cosine_similarity(matrix)
  best_sim = -1
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim > best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [13]:
print(df)
print ("------")
doc_id = 1
print("Texto: ", df.loc[doc_id]['texts'])
print("Texto mais parecido: ", df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts      classes
0   O Grêmio é tricampeão da Libertadores da América       Grêmio
1  O Corinthians ganhou a Libertadores uma única vez  Corinthians
------
Texto:  O Corinthians ganhou a Libertadores uma única vez
Texto mais parecido:  O Grêmio é tricampeão da Libertadores da América


### Jaccard

"O índice de Jaccard é uma estatística para comparar e medir a semelhança entre dois conjuntos diferentes. É uma proporção da interseção de dois conjuntos sobre a união deles.

Se você tiver um número finito representativo de elementos para uma observação específica e quiser comparar essa observação com outra observação, poderá contar o número de itens comuns a esses dois conjuntos. É um ajuste natural para comparar postagens se você conhece as *tags* representativas das postagens para medir o quão semelhantes dois artigos são em termos de *tags*."

Fonte: http://bugra.github.io/work/notes/2017-02-07/similarity-via-jaccard-index/

In [14]:
from sklearn.metrics import pairwise_distances

In [15]:
def most_similar(id_doc, matrix):
  matrix_sim = 1 - pairwise_distances(matrix, metric='jaccard') # como é medida de distância (valor entre 0 e 1), utilizar o complemento
  best_sim = -1
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim > best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [16]:
matrix_sim = 1 - pairwise_distances(rep_array, metric='jaccard')
matrix_sim

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/pairwise.py:2466: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


array([[1., 1.],
       [1., 1.]])

In [18]:
import warnings
warnings.filterwarnings("ignore") # não imprimir o warning por não utilizar valores binários

print(df)
print ("------")
doc_id = 1
print("Texto: ", df.loc[doc_id]['texts'])
print("Texto mais parecido: ", df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts      classes
0   O Grêmio é tricampeão da Libertadores da América       Grêmio
1  O Corinthians ganhou a Libertadores uma única vez  Corinthians
------
Texto:  O Corinthians ganhou a Libertadores uma única vez
Texto mais parecido:  O Grêmio é tricampeão da Libertadores da América


### Jaccard backup (testar depois com os mesmos textos das outras)

In [20]:
def jaccard_similarity(x,y):
  """ retorna a similaridade de jaccard entre duas listas """
  intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
  union_cardinality = len(set.union(*[set(x), set(y)]))
  return intersection_cardinality/float(union_cardinality)

texto1 = rep_array[1]
texto2 = rep_array[0]

print(texto1)
print(texto2)

print(jaccard_similarity(texto1, texto2))

print(matrix_sim[1][0])

[1]
[1]
1.0
1.0


### Euclidiana

In [21]:
def most_similar(id_doc, matrix):
  matrix_sim = pairwise_distances(matrix, metric='euclidean')
  best_sim = 99999999
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim <= best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [22]:
matrix_sim = pairwise_distances(rep_array, metric='euclidean')
matrix_sim

array([[0., 0.],
       [0., 0.]])

In [23]:
print(df)
print ("------")
doc_id = 1
#df.loc[doc_id]['texts']
df.loc[most_similar(doc_id, rep_array)]['texts']

                                               texts      classes
0   O Grêmio é tricampeão da Libertadores da América       Grêmio
1  O Corinthians ganhou a Libertadores uma única vez  Corinthians
------


'O Grêmio é tricampeão da Libertadores da América'

# Agradecimentos

Curso de Tópicos em Inteligência Artificial (Rafael G. Rossi)
*   https://github.com/ragero/topicos_inteligencia_artificial_2_2020

Similaridade Textual (Alex Sherman)
*   https://colab.research.google.com/drive/12x2ygJk2ciN7Wco2_g00MR20jPuMR9_K




